package br.com.orlandoburli.core.dao.financeiro.contasapagar;

import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;

import br.com.orlandoburli.core.dao.BaseCadastroDAO;
import br.com.orlandoburli.core.vo.financeiro.contasapagar.ContaPagarVO;

public class ContaPagarDAO extends BaseCadastroDAO<ContaPagarVO> {

	public ResultSet getListContasResumo(Integer CodigoEmpresa, Integer CodigoLoja, Integer CodigoEmpresaGlobal, Integer CodigoLojaGlobal, Date DataInicial, Date DataFinal, String FlgContasOcultas, String Lojas) throws SQLException {
		
		String sql = getSqlContaResumo();
		
		sql = sql.replace("$P{CodigoEmpresa}", CodigoEmpresa==null?"NULL":CodigoEmpresa.toString());
		sql = sql.replace("$P{CodigoLoja}", CodigoLoja==null?"NULL":CodigoLoja.toString());
		
		sql = sql.replace("$P{CodigoEmpresaGlobal}", CodigoEmpresaGlobal==null?"NULL":CodigoEmpresaGlobal.toString());
		sql = sql.replace("$P{CodigoLojaGlobal}", CodigoLojaGlobal==null?"NULL":CodigoLojaGlobal.toString());
		
		sql = sql.replace("$P{DataInicial}", DataInicial==null?"NULL":"'" + DataInicial.toString() + "'");
		sql = sql.replace("$P{DataFinal}", DataFinal==null?"NULL":"'" + DataFinal.toString() + "'");
		
		sql = sql.replace("$P{FlgContasOcultas}", FlgContasOcultas==null?"NULL":"'" + FlgContasOcultas + "'");
		
		sql = sql.replace("$P{Lojas}", Lojas);
		
		try {
			return getRowSet(sql);
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}
		return null;
	}
	
	private String getSqlContaResumo() {

		String sql = "SELECT a.*,\n"
				+ "       (SELECT SUM(Valor) FROM\n"
				+ "       (SELECT CASE WHEN rat.valorrateio IS NULL THEN p.valorcontapagar ELSE 0 END as valor\n"
				+ "          FROM personalerp.contapagar p\n"
				+ "          JOIN personalerp.planoconta ap on ap.codigoplanoconta = p.codigoplanoconta\n"
				+ "          LEFT JOIN personalerp.rateiocontapagar rat on rat.codigoempresa       = p.codigoempresa\n"
				+ "                                                    and rat.codigoloja          = p.codigoloja\n"
				+ "                                                    and rat.codigocontapagar    = p.codigocontapagar\n"
				+ "                                                    and rat.codigoempresarateio = p.codigoempresa\n"
				+ "                                                    and rat.codigolojarateio    = p.codigoloja\n"
				+ "         WHERE (ap.numeroplanoconta ilike a.numeroplanoconta || '.%' OR ap.codigoplanoconta = a.codigoplanoconta)\n"
				+ "         AND p.SituacaoContaPagar <> 'C'\n"
				+ "           AND p.DataVencimentoContaPagar >= $P{DataInicial}\n"
				+ "           AND p.DataVencimentoContaPagar <= $P{DataFinal}\n"
				+ "           AND (p.CodigoEmpresa = $P{CodigoEmpresa} OR $P{CodigoEmpresa} IS NULL)\n"
				+ "           AND (p.CodigoLoja    = $P{CodigoLoja}    OR $P{CodigoLoja}    IS NULL)\n"
				+ "           AND ((p.CodigoEmpresa, p.CodigoLoja) IN ($P{Lojas}))\n"
				+ "       AND (p.FlagResumoContaPagar = 'S' OR $P{FlgContasOcultas} = 'S')\n"
				+ "\n"
				+ "         UNION ALL\n"
				+ "\n"
				+ "  SELECT rat.valorrateio\n"
				+ "          FROM personalerp.contapagar p\n"
				+ "          JOIN personalerp.planoconta ap on ap.codigoplanoconta = p.codigoplanoconta\n"
				+ "          JOIN personalerp.rateiocontapagar rat on rat.codigoempresa       = p.codigoempresa\n"
				+ "                                               and rat.codigoloja          = p.codigoloja\n"
				+ "                                               and rat.codigocontapagar    = p.codigocontapagar\n"
				+ "\n"
				+ "\n"
				+ "         WHERE (ap.numeroplanoconta ilike a.numeroplanoconta || '.%' OR ap.codigoplanoconta = a.codigoplanoconta)\n"
				+ "         AND p.SituacaoContaPagar <> 'C'\n"
				+ "         AND p.DataVencimentoContaPagar >= $P{DataInicial}\n"
				+ "           AND p.DataVencimentoContaPagar <= $P{DataFinal}\n"
				+ "           AND (rat.CodigoEmpresaRateio = $P{CodigoEmpresa} OR $P{CodigoEmpresa} IS NULL)\n"
				+ "           AND (rat.CodigoLojaRateio    = $P{CodigoLoja}    OR $P{CodigoLoja}    IS NULL)\n"
				+ "           AND ((rat.CodigoEmpresa, rat.CodigoLoja) IN ($P{Lojas}))\n"
				+ "       AND (p.FlagResumoContaPagar = 'S' OR $P{FlgContasOcultas} = 'S')\n"
				+ "  ) as Debitos ) as ValorDebito,\n"
				+ "\n"
				+ "  (SELECT SUM(Valor) FROM\n"
				+ "       (SELECT CASE WHEN rat.valorrateio IS NULL THEN p.valorcontapagar ELSE 0 END as valor\n"
				+ "          FROM personalerp.contapagar p\n"
				+ "          JOIN personalerp.planoconta ap on ap.codigoplanoconta = p.codigoplanoconta\n"
				+ "          LEFT JOIN personalerp.rateiocontapagar rat on rat.codigoempresa       = p.codigoempresa\n"
				+ "                                                    and rat.codigoloja          = p.codigoloja\n"
				+ "                                                    and rat.codigocontapagar    = p.codigocontapagar\n"
				+ "                                                    and rat.codigoempresarateio = p.codigoempresa\n"
				+ "                                                    and rat.codigolojarateio    = p.codigoloja\n"
				+ "         WHERE (ap.numeroplanoconta ilike a.numeroplanoconta || '.%' OR ap.codigoplanoconta = a.codigoplanoconta)\n"
				+ "     AND p.SituacaoContaPagar <> 'C'\n"
				+ "           AND p.DataVencimentoContaPagar >= $P{DataInicial}\n"
				+ "           AND p.DataVencimentoContaPagar <= $P{DataFinal}\n"
				+ "           AND (p.CodigoEmpresa = $P{CodigoEmpresa} OR $P{CodigoEmpresa} IS NULL)\n"
				+ "           AND (p.CodigoLoja    = $P{CodigoLoja}    OR $P{CodigoLoja}    IS NULL)\n"
				+ "           AND ((p.CodigoEmpresa, p.CodigoLoja) IN ($P{Lojas}))\n"
				+ "           AND (p.FlagResumoContaPagar = 'S' OR $P{FlgContasOcultas} = 'S')\n"
				+ "\n"
				+ "         UNION ALL\n"
				+ "\n"
				+ "  SELECT rat.valorrateio\n"
				+ "          FROM personalerp.contapagar p\n"
				+ "          JOIN personalerp.planoconta ap on ap.codigoplanoconta = p.codigoplanoconta\n"
				+ "          JOIN personalerp.rateiocontapagar rat on rat.codigoempresa       = p.codigoempresa\n"
				+ "                                               and rat.codigoloja          = p.codigoloja\n"
				+ "                                               and rat.codigocontapagar    = p.codigocontapagar\n"
				+ "\n"
				+ "\n"
				+ "         WHERE (ap.numeroplanoconta ilike a.numeroplanoconta || '.%' OR ap.codigoplanoconta = a.codigoplanoconta)\n"
				+ "         AND p.SituacaoContaPagar <> 'C'\n"
				+ "         AND p.DataVencimentoContaPagar >= $P{DataInicial}\n"
				+ "           AND p.DataVencimentoContaPagar <= $P{DataFinal}\n"
				+ "           AND (rat.CodigoEmpresaRateio = $P{CodigoEmpresa} OR $P{CodigoEmpresa} IS NULL)\n"
				+ "           AND (rat.CodigoLojaRateio    = $P{CodigoLoja}    OR $P{CodigoLoja}    IS NULL)\n"
				+ "           AND ((rat.CodigoEmpresa, rat.CodigoLoja) IN ($P{Lojas}))\n"
				+ "       AND (p.FlagResumoContaPagar = 'S' OR $P{FlgContasOcultas} = 'S')\n"
				+ "  ) as Debitos )\n"
				+ "         /\n"
				+ "   (SELECT SUM(p.valorcontapagar)\n"
				+ "          FROM personalerp.contapagar p\n"
				+ "          JOIN personalerp.planoconta ap on ap.codigoplanoconta = p.codigoplanoconta\n"
				+ "         WHERE ap.numeroplanoconta ILIKE\n"
				+ "    (CASE WHEN a.codigoplanocontapai IS NULL THEN a.numeroplanoconta || '.%'\n"
				+ "                 ELSE substring(a.numeroplanoconta, 1, position('.' in a.numeroplanoconta)) || '%' END)\n"
				+ "          AND p.SituacaoContaPagar <> 'C'\n"
				+ "          AND p.DataVencimentoContaPagar >= $P{DataInicial}\n"
				+ "          AND p.DataVencimentoContaPagar <= $P{DataFinal}\n"
				+ "          AND (p.CodigoEmpresa = $P{CodigoEmpresa} OR $P{CodigoEmpresa} IS NULL)\n"
				+ "          AND (p.CodigoLoja    = $P{CodigoLoja}    OR $P{CodigoLoja}    IS NULL)\n"
				+ "           AND ((p.CodigoEmpresa, p.CodigoLoja) IN ($P{Lojas}))\n"
				+ "      AND (p.FlagResumoContaPagar = 'S' OR $P{FlgContasOcultas} = 'S')\n"
				+ "  )\n"
				+ "\n"
				+ "  as percentualdebito\n"
				+ "  ,\n"
				+ "       (SELECT SUM(p.valorcontareceber)\n"
				+ "          FROM personalerp.contareceber p\n"
				+ "         WHERE p.codigoplanoconta = a.codigoplanoconta\n"
				+ "           AND p.SituacaoContaReceber <> 'C'\n"
				+ "           AND p.DataVencimentoContaReceber >= $P{DataInicial}\n"
				+ "           AND p.DataVencimentoContaReceber <= $P{DataFinal}\n"
				+ "           AND (p.CodigoEmpresa = $P{CodigoEmpresa} OR $P{CodigoEmpresa} IS NULL)\n"
				+ "           AND (p.CodigoLoja    = $P{CodigoLoja}    OR $P{CodigoLoja}    IS NULL)\n"
				+ "           AND ((p.CodigoEmpresa, p.CodigoLoja) IN ($P{Lojas}))\n"
				+ "        ) as valorcredito,\n"
				+ "\n"
				+ "        (SELECT SUM(p.valorcontareceber)\n"
				+ "           FROM personalerp.contareceber p\n"
				+ "           JOIN personalerp.planoconta ap on ap.codigoplanoconta = p.codigoplanoconta\n"
				+ "          WHERE (ap.numeroplanoconta ilike a.numeroplanoconta || '.%'\n"
				+ "             OR ap.codigoplanoconta = a.codigoplanoconta)\n"
				+ "            AND p.SituacaoContaReceber <> 'C'\n"
				+ "            AND p.DataVencimentoContaReceber >= $P{DataInicial}\n"
				+ "            AND p.DataVencimentoContaReceber <= $P{DataFinal}\n"
				+ "            AND (p.CodigoEmpresa = $P{CodigoEmpresa} OR $P{CodigoEmpresa} IS NULL)\n"
				+ "            AND (p.CodigoLoja    = $P{CodigoLoja}    OR $P{CodigoLoja}    IS NULL)\n"
				+ "           AND ((p.CodigoEmpresa, p.CodigoLoja) IN ($P{Lojas}))\n"
				+ "         )\n"
				+ "         /\n"
				+ "   (SELECT SUM(p.valorcontareceber)\n"
				+ "            FROM personalerp.contareceber p\n"
				+ "            JOIN personalerp.planoconta ap on ap.codigoplanoconta = p.codigoplanoconta\n"
				+ "           WHERE ap.numeroplanoconta ILIKE\n"
				+ "    (CASE WHEN a.codigoplanocontapai IS NULL THEN a.numeroplanoconta || '.%'\n"
				+ "     ELSE substring(a.numeroplanoconta, 1, position('.' in a.numeroplanoconta)) || '%' END)\n"
				+ "             AND p.SituacaoContaReceber <> 'C'\n"
				+ "             AND p.DataVencimentoContaReceber >= $P{DataInicial}\n"
				+ "             AND p.DataVencimentoContaReceber <= $P{DataFinal}\n"
				+ "             AND (p.CodigoEmpresa = $P{CodigoEmpresa} OR $P{CodigoEmpresa} IS NULL)\n"
				+ "             AND (p.CodigoLoja    = $P{CodigoLoja}    OR $P{CodigoLoja}    IS NULL)\n"
				+ "           AND ((p.CodigoEmpresa, p.CodigoLoja) IN ($P{Lojas}))\n"
				+ "          )\n"
				+ "  as percentualcredito,\n"
				+ "\n"
				+ "\n"
				+ "  (SELECT SUM(Valor) FROM\n"
				+ "       (SELECT CASE WHEN rat.valorrateio IS NULL THEN p.valorcontapagar ELSE 0 END as valor\n"
				+ "          FROM personalerp.contapagar p\n"
				+ "          JOIN personalerp.planoconta ap on ap.codigoplanoconta = p.codigoplanoconta\n"
				+ "          LEFT JOIN personalerp.rateiocontapagar rat on rat.codigoempresa       = p.codigoempresa\n"
				+ "                                                    and rat.codigoloja          = p.codigoloja\n"
				+ "                                                    and rat.codigocontapagar    = p.codigocontapagar\n"
				+ "                                                    and rat.codigoempresarateio = p.codigoempresa\n"
				+ "                                                    and rat.codigolojarateio    = p.codigoloja\n"
				+ "         WHERE (ap.numeroplanoconta ilike a.numeroplanoconta || '.%' OR ap.codigoplanoconta = a.codigoplanoconta)\n"
				+ "     AND p.SituacaoContaPagar <> 'C'\n"
				+ "           AND p.DataVencimentoContaPagar >= $P{DataInicial}\n"
				+ "           AND p.DataVencimentoContaPagar <= $P{DataFinal}\n"
				+ "           AND (p.CodigoEmpresa = $P{CodigoEmpresa} OR $P{CodigoEmpresa} IS NULL)\n"
				+ "           AND (p.CodigoLoja    = $P{CodigoLoja}    OR $P{CodigoLoja}    IS NULL)\n"
				+ "           AND ((p.CodigoEmpresa, p.CodigoLoja) IN ($P{Lojas}))\n"
				+ "       AND (p.FlagResumoContaPagar = 'S' OR $P{FlgContasOcultas} = 'S')\n"
				+ "\n"
				+ "         UNION ALL\n"
				+ "\n"
				+ "  SELECT rat.valorrateio\n"
				+ "          FROM personalerp.contapagar p\n"
				+ "          JOIN personalerp.planoconta ap on ap.codigoplanoconta = p.codigoplanoconta\n"
				+ "          JOIN personalerp.rateiocontapagar rat on rat.codigoempresa       = p.codigoempresa\n"
				+ "                                               and rat.codigoloja          = p.codigoloja\n"
				+ "                                               and rat.codigocontapagar    = p.codigocontapagar\n"
				+ "\n"
				+ "\n"
				+ "         WHERE (ap.numeroplanoconta ilike a.numeroplanoconta || '.%' OR ap.codigoplanoconta = a.codigoplanoconta)\n"
				+ "     AND p.SituacaoContaPagar <> 'C'\n"
				+ "     AND p.DataVencimentoContaPagar >= $P{DataInicial}\n"
				+ "           AND p.DataVencimentoContaPagar <= $P{DataFinal}\n"
				+ "           AND (rat.CodigoEmpresaRateio = $P{CodigoEmpresa} OR $P{CodigoEmpresa} IS NULL)\n"
				+ "           AND (rat.CodigoLojaRateio    = $P{CodigoLoja}    OR $P{CodigoLoja}    IS NULL)\n"
				+ "           AND ((rat.CodigoEmpresa, rat.CodigoLoja) IN ($P{Lojas}))\n"
				+ "       AND (p.FlagResumoContaPagar = 'S' OR $P{FlgContasOcultas} = 'S')\n"
				+ "  ) as Debitos )\n"
				+ "  /\n"
				+ "   (SELECT SUM(p.valorcontareceber)\n"
				+ "            FROM personalerp.contareceber p\n"
				+ "            JOIN personalerp.planoconta ap on ap.codigoplanoconta = p.codigoplanoconta\n"
				+ "           WHERE 1=1\n"
				+ "             AND p.SituacaoContaReceber <> 'C'\n"
				+ "             AND p.DataVencimentoContaReceber >= $P{DataInicial}\n"
				+ "             AND p.DataVencimentoContaReceber <= $P{DataFinal}\n"
				+ "             AND (p.CodigoEmpresa = $P{CodigoEmpresaGlobal} OR $P{CodigoEmpresaGlobal} IS NULL)\n"
				+ "             AND (p.CodigoLoja    = $P{CodigoLojaGlobal}    OR $P{CodigoLojaGlobal}    IS NULL)\n"
				+ "             AND ((p.CodigoEmpresa, p.CodigoLoja) IN ($P{Lojas}))\n"
				+ "          )\n"
				+ "  as PercentualDebitoSobreReceita\n"
				+ "\n"
				+ "  from personalerp.planoconta a\n"
				+ "  left join personalerp.planoconta b on a.codigoplanocontapai = b.codigoplanoconta\n"
				+ " order by coalesce(b.numeroplanoconta, a.numeroplanoconta), case when b.numeroplanoconta is null then a.numeroplanoconta else a.nomeplanoconta end , a.numeroplanoconta\n"
				+ "\n" + "";

		return sql;
	}

}