/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-09-16 04:25:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web.pages.acesso.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<title>Personaler ERP - Orlando Burli Projetos de TI Personalizados</title>\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/web/assets/css/main.css\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/web/assets/css/login.css\">\n");
      out.write("\t<link rel=\"shortcut icon\" type=\"image/png\" href=\"/web/assets/img/logo.png\">\n");
      out.write("\n");
      out.write("\t<!-- Plugin JQuery e JQuery UI-->\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/web/assets/jquery-ui/js/jquery-1.9.1.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/web/assets/jquery-ui/js/jquery-ui-1.10.3.custom.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/web/assets/js/geral.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/web/assets/js/login.js\" type=\"text/javascript\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div id=\"content-all\">\n");
      out.write("\n");
      out.write("\t\t<div id=\"content-logo\">\n");
      out.write("\t\t\t<div id=\"div-logo\"></div>\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"info-logo\">\n");
      out.write("\t\t\t\t<p>PersonalERP - Orlando Burli</p>\n");
      out.write("\t\t\t\t<p>Projetos de TI Personalizados</p>\n");
      out.write("\t\t\t\t<p>(65) 9946 - 3093</p>\n");
      out.write("\t\t\t\t<p><a href=\"mailto:contato@orlandoburli.com.br\">contato@orlandoburli.com.br</a></p>\n");
      out.write("\t\t\t</div>\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div id=\"form-login\" class=\"form\">\n");
      out.write("\t\t\t<div class=\"form-header\">LOGIN</div>\n");
      out.write("\t\t\t<div class=\"form-content\">\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t<label for=\"Login\">Login:</label>\n");
      out.write("\t\t\t\t\t<input id=\"Login\" type=\"text\" maxlength=\"20\" autofocus=\"autofocus\"/>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t<label for=\"Senha\">Senha:</label>\n");
      out.write("\t\t\t\t\t<input id=\"Senha\" type=\"password\" />\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"form-bottom\"></div>\n");
      out.write("\t\t\t<div class=\"form-botoes\">\n");
      out.write("\t\t\t\t<button id=\"Entrar\">Entrar</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div id=\"form-perfil\" class=\"form\">\n");
      out.write("\t\t\t<div class=\"form-header\">PERFIL</div>\n");
      out.write("\t\t\t<div class=\"form-content\">\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t<label for=\"Perfil\">Perfil:</label>\n");
      out.write("\t\t\t\t\t<select id=\"Perfil\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\">[SELECIONE UM PERFIL]</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">Administrador</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">Auxiliar Estoque</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">Auxiliar Financeiro</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">Gerente Loja</option>\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"form-bottom\"></div>\n");
      out.write("\t\t\t<div class=\"form-botoes\">\n");
      out.write("\t\t\t\t<button id=\"SelecionarPerfil\">Avan&ccedil;ar</button>\n");
      out.write("\t\t\t\t<button id=\"VoltarLogin\">Voltar</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div id=\"form-empresa\" class=\"form\">\n");
      out.write("\t\t\t<div class=\"form-header\">EMPRESA</div>\n");
      out.write("\t\t\t<div class=\"form-content\">\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t<label for=\"Empresa\">Empresa:</label>\n");
      out.write("\t\t\t\t\t<select id=\"Empresa\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\">[SELECIONE UMA EMPRESA]</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">EMPRESA 01</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">EMPRESA 02</option>\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"form-bottom\"></div>\n");
      out.write("\t\t\t<div class=\"form-botoes\">\n");
      out.write("\t\t\t\t<button id=\"SelecionarEmpresa\">Avan&ccedil;ar</button>\n");
      out.write("\t\t\t\t<button id=\"VoltarPerfil\">Voltar</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div id=\"form-loja\" class=\"form\">\n");
      out.write("\t\t\t<div class=\"form-header\">LOJA</div>\n");
      out.write("\t\t\t<div class=\"form-content\">\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t<label for=\"Loja\">Loja:</label>\n");
      out.write("\t\t\t\t\t<select id=\"Loja\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\">[SELECIONE UMA LOJA]</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">LOJA 01</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">LOJA 02</option>\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"form-bottom\"></div>\n");
      out.write("\t\t\t<div class=\"form-botoes\">\n");
      out.write("\t\t\t\t<button id=\"SelecionarLoja\">Entrar</button>\n");
      out.write("\t\t\t\t<button id=\"VoltarEmpresa\">Voltar</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div id=\"form-loading\" class=\"form\">\n");
      out.write("\t\t\t<div class=\"form-header\"></div>\n");
      out.write("\t\t\t<div class=\"form-content form-loading-content\">\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t<label>Por favor aguarde, logando no sistema...</label>\n");
      out.write("\t\t\t\t\t<div id=\"div-loading-bar\"></div>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"form-bottom\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div id=\"form-mensagem\" class=\"mensagem\">\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
