/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-09-16 04:26:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web.pages.estoque.produto;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class produtoconsulta_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<aside>\n");
      out.write("\t<label class=\"TituloTela\">Consulta de Produtos</label>\n");
      out.write("\t\n");
      out.write("\t<div class=\"FormularioConsulta FormularioGeral\">\n");
      out.write("\t\t\n");
      out.write("\t\t<div id=\"CamposFiltro\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<fieldset>\n");
      out.write("\t\t\t\t<legend>Pesquisar por</legend>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<select id=\"ParametroPesquisa\">\n");
      out.write("\t\t\t\t\t<option value=\"Nome\">Nome</option>\n");
      out.write("\t\t\t\t\t<option value=\"Referencia\">Referência</option>\n");
      out.write("\t\t\t\t\t<option value=\"Codigo\">Código</option>\n");
      out.write("\t\t\t\t</select> <input id=\"PesquisarPor\" type=\"text\" autofocus=\"autofocus\" autocomplete=\"off\"/>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<button title=\"Clique para pesquisar [Atalho: ENTER]\" class=\"BotaoPesquisar\">Pesquisar</button>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</fieldset>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"DataGridConsulta\" data-page=\"produtoconsulta.grid.erp\" data-page-size=\"10\" data-detail-page=\"produtocadastro.erp\"></div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"FormularioBotoesNavegacaoGrid\">\n");
      out.write("\t\t\t<button class=\"BotaoNavegacaoPrimeiro\" title=\"Primeiro [Home]\"></button>\n");
      out.write("\t\t\t<button class=\"BotaoNavegacaoAnterior\" title=\"Anterior [&larr;/PgUp]\"></button>\n");
      out.write("\t\t\t<button class=\"BotaoNavegacaoProximo\" title=\"Próximo [&rarr;/PgDown]\"></button>\n");
      out.write("\t\t\t<button class=\"BotaoNavegacaoUltimo\" title=\"Último [End]\"></button>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div class=\"FormularioBotoes\">\n");
      out.write("\t\t<button type=\"button\" class=\"BotaoNovo\" title=\"Novo Registro (Ctrl + N)\">Novo</button>\n");
      out.write("\t\t<button type=\"button\" class=\"BotaoEditar\" title=\"Editar Registro Selecionado (Ctrl + E)\">Editar</button>\n");
      out.write("\t\t<button type=\"button\" class=\"BotaoExcluir\" title=\"Excluir Registro Selecionado (Ctrl + Del)\">Excluir</button>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("</aside>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
